# Generated by Django 5.0 on 2024-04-30 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('running_kilometers', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='pending', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('job_card_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobcard')),
            ],
        ),
    ]
