# Generated by Django 5.0 on 2024-05-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='created_by',
        ),
    ]
